/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab02;


import java.util.Random;

public class Library {
    public boolean someLibraryMethod() {
        return true;

            }

    public  int[] roll (int ints) {
        Random r = new Random();
        int low = 1;
        int high = 6;

        int [] rolls = new int[ints];
        for (int i = 0 ; i < ints ; i++) {
        rolls[i] = r.nextInt(high-low) + low ;
        }
        return rolls;
        }


    }



