/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static int linter (Path paths){
        int errors = 0;
        int lineIncrease = 0;
        try {
            List<String> linesNum = Files.readAllLines(paths);
            for (String line : linesNum) {
                lineIncrease++;
                if (!(line.isEmpty())) {
                    if (line.contains("if") || line.contains("else")||line.contains(";")||line.contains("}")||line.contains("{")) {
                    } else {
                        System.out.println(" Line "+ lineIncrease + " : Missing semicolon.");

                        errors++;
                    }
                }
            }
        } catch (IOException exception) {
            System.out.println("error with reading file ..! ");
        }
    return errors;
    }

}
