/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {


    @Test public void constructorRes() {


        Restaurant restaurant = new Restaurant("FireFly",4,"$");
        String name = "FireFly";
        String price = "$";
        assertEquals(name,restaurant.getName());
        assertEquals(4,restaurant.getRating());
        assertEquals(price,restaurant.getPriceCategory());
    }

    @Test public void toStringTest() {
        Restaurant restaurant = new Restaurant("FireFly",4,"$");
        assertEquals("Restaurant{name='FireFly', rating=4, category='$'}",String.valueOf(restaurant));
    }

    @Test public void addReview(){
        Restaurant restaurant = new Restaurant("FireFly",4,"$");
        Review review = new Review(" can be more better than this ","Khair Shkokany",3);
        restaurant.addReview(review);
        assertEquals( restaurant.getReviews().size(), 1, restaurant.getReviews().size());

    }

    @Test public void constructorReview() {
        Review review = new Review(" can be more better than this ","Khair Shkokany",3);
        assertEquals(" can be more better than this ",review.getBody());
        assertEquals("Khair Shkokany",review.getAuthor());
        assertEquals(3,review.getRating());
    }


@Test public void toStringReview() {
    Review review = new Review("The burger is good but not juciy so you can be more better than this ","Khair Shkokany",3);
    assertEquals("Review{body='The burger is good but not juciy so you can be more better than this ', author='Khair Shkokany', rating=3}",String.valueOf(review));
}




}
